"use client";
require("dotenv").config();
import { NextUIProvider } from "@nextui-org/react";
import { Provider } from 'react-redux'
import { store } from "@/store/store";
import Nev from "@/app/Components/Nev";

import "./globals.css";
import Footer from "./Components/Footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <NextUIProvider>
          <Provider store={store}>
            <Nev/>
          {children}
        
          </Provider>
        </NextUIProvider>
      </body>
    </html>
  );
}
